create table if not exists usuario
(
    uid      text        not null primary key,
    username varchar(40) not null,
    password varchar     not null,
    email    varchar     not null unique,
    role     varchar     not null,
    enable   boolean     not null default false
);

create table if not exists token
(
    id          text      not null primary key,
    usuario_id  text      not null unique references usuario (uid) on delete cascade on update cascade,
    createdAt   timestamp not null,
    expiredAt   timestamp not null,
    confirmedAt timestamp
);

create table if not exists image
(
    id       integer primary key generated by default as identity,
    image    bytea   not null,
    filetype varchar not null,
    filename varchar not null
);

CREATE TABLE if not exists categoria
(
    id     integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome   varchar(30) unique  NOT NULL,
    imagem text                NOT NULL
);
CREATE TABLE if not exists produto
(
    id          integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome        varchar(50)         NOT NULL,
    preco       float8              NOT NULL,
    quantidade  integer             not null,
    createdAt   timestamp           NOT NULL,
    likes       integer             NOT NULL default 0,
    category_id integer             NOT NULL references categoria (id) on delete cascade on update cascade
);

CREATE TABLE if not exists produto_imagem
(
    produto_id integer NOT NULL references produto (id) on delete cascade on update cascade,
    imagem     text    NOT NULL
);


CREATE TABLE if not exists usuario_produto
(
    id         integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    produto_id integer             NOT NULL references produto (id) on delete cascade on update cascade,
    usuario_id text                NOT NULL references usuario (uid) on delete cascade on update cascade
);

CREATE TABLE if not exists usuario_cart
(
    id         integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    produto_id integer             NOT NULL references produto (id) on delete cascade on update cascade,
    usuario_id text                NOT NULL references usuario (uid) on delete cascade on update cascade
);
